[package]
name = "pkill"
description = "simple tool to kill processes"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.26"
clap = { version = "4.0", features = ["derive"] }
thiserror = "1.0"