[package]
name = "pkill"
description = "Simple tool to kill processes"
version = "0.1.0"
edition = "2021"
authors = ["zmrl"]
license = "MIT"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
sysinfo = "0.26"

[build-dependencies]
clap = { version = "4.0", features = ["derive"] }
clap_mangen = "0.2.3"
clap_complete = "4.0.3"
sysinfo = "0.26"
