[package]
name = "pkill-cli"
version = "0.1.0"
description = "Command-line interface for pkill"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.0", features = ["derive"] }
pkill-lib = { path = "../pkill-lib" }

